/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import hgu.isel.ByteParser;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ByteParserTest {
    @Test void appHasAGreeting() {
        ByteParser classUnderTest = new ByteParser();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
