/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import hgu.isel.ByteTok;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class ByteTokTest {
    @Test void appHasAGreeting() {
        ByteTok classUnderTest = new ByteTok();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
