/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import hgu.isel.ByteTok;
import org.junit.jupiter.api.Test;

import java.io.PrintStream;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class ByteTokTest {
    @Test void test1() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/Filter.class"));
    }

    @Test void test2() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/FilterChain.class"));
    }

    @Test void test3() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/FilterConfig.class"));
    }

    @Test void test4() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/GenericServlet.class"));
    }

    @Test void test5() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/RequestDispatcher.class"));
    }

    @Test void test6() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/Servlet.class"));
    }

    @Test void test7() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/ServletConfig.class"));
    }

    @Test void test8() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/ServletContext.class"));
    }

    @Test void test9() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/ServletContextAttributeEvent.class"));
    }

    @Test void test10() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/ServletContextAttributeListener.class"));
    }

    @Test void test11() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/ServletContextEvent.class"));
    }

    @Test void test12() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/ServletContextListener.class"));
    }

    @Test void test13() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/ServletException.class"));
    }

    @Test void test14() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/ServletInputStream.class"));
    }

    @Test void test15() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/ServletOutputStream.class"));
    }

    @Test void test16() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/ServletRequest.class"));
    }

    @Test void test17() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/ServletRequestAttributeEvent.class"));
    }

    @Test void test18() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/ServletRequestAttributeListener.class"));
    }

    @Test void test19() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/ServletRequestEvent.class"));
    }

    @Test void test20() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/ServletRequestListener.class"));
    }
    @Test void test21() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/ServletRequestWrapper.class"));
    }
    @Test void test22() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/ServletResponse.class"));
    }
    @Test void test23() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/ServletResponseWrapper.class"));
    }
    @Test void test24() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/SingleThreadModel.class"));
    }
    @Test void test25() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/UnavailableException.class"));
    }
    @Test void test26() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/AbstractRequestParameters.class"));
    }

    @Test void test28() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/FlexibleEnum.class"));
    }

    @Test void test29() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/ValidationError.class"));
    }

    @Test void test30() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/Training.class"));
    }

    @Test void test31() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/UserBonus.class"));
    }

    @Test void test32() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/UserSkill.class"));
    }

    @Test void test33() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/WebhookEventType.class"));
    }

    @Test void test34() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/BaseForm.class"));
    }

    @Test void test35() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/BaseHttpServlet.class"));
    }

    @Test void test36() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/CometDLoadClient.class"));
    }

    @Test void test38() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/AbstractResolveDependencies.class"));
    }

    @Test void test39() {
        ByteTok classUnderTest = new ByteTok();
        assertDoesNotThrow(() -> classUnderTest.run("/Users/ehdrb01/Desktop/HGU/capstone/ByteParser/byte/app/src/codes/Revision.class"));
    }

}
