/*
 * This source file was generated by the Gradle 'init' task
 */
package hgu.isel;

import hgu.isel.reader.ByteReader;

public class ByteParser {
    byte[] bytes;

    public static void main(String[] args) {
        ByteParser parser = new ByteParser();
        parser.run(args[0]);
    }

    public void run(String path) {
        ByteReader byteReader = new ByteReader(path);
        bytes = byteReader.readClassFile();
    }
}
